/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as StickerStatsIndexImport } from './routes/sticker-stats/index'
import { Route as AdIndexImport } from './routes/ad/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const StickerStatsIndexRoute = StickerStatsIndexImport.update({
  path: '/sticker-stats/',
  getParentRoute: () => rootRoute,
} as any)

const AdIndexRoute = AdIndexImport.update({
  path: '/ad/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/ad/': {
      id: '/ad/'
      path: '/ad'
      fullPath: '/ad'
      preLoaderRoute: typeof AdIndexImport
      parentRoute: typeof rootRoute
    }
    '/sticker-stats/': {
      id: '/sticker-stats/'
      path: '/sticker-stats'
      fullPath: '/sticker-stats'
      preLoaderRoute: typeof StickerStatsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AdIndexRoute,
  StickerStatsIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/ad/",
        "/sticker-stats/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/ad/": {
      "filePath": "ad/index.tsx"
    },
    "/sticker-stats/": {
      "filePath": "sticker-stats/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
